language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install poetry
    - poetry build
    - pip install dist/*.whl

script:
    - poetry run nosetests --with-coverage --cover-package=decisiveml -d